---
- name: 'Create user keypairs'
  openstack.cloud.keypair:
    name: "{{ item.key }}"
    state: present
    public_key: "{{ item.value.key }}"
  with_dict: "{{ users }}"
  when: users is defined and item.value.key is defined
