---
- name: 'Create networks'
  openstack.cloud.network:
    admin_state_up: "{{ item['admin_state_up'] | default('yes') }}"
    external: "{{ item['external'] | default('no') }}"
    project: "{{ item['project'] | default(omit) }}"
    provider_network_type: "{{ item['provider_network_type'] | default(omit) }}"
    provider_physical_network: "{{ item['provider_physical_network'] | default(omit) }}"
    provider_segmentation_id: "{{ item['provider_segmentation_id'] | default(omit) }}"
    shared: "{{ item['shared'] | default('no') }}"
    cloud: "{{ item.cloud | default(omit) }}"
    state: "{{ item['state'] | default('present') }}"
    name: "{{ item.network_name }}"
  with_items: "{{ os_networks }}"
  when: os_networks is defined

- name: 'Create subnets'
  openstack.cloud.subnet:
    allocation_pool_end: "{{ item[1]['allocation_pool_end'] | default(omit) }}"
    allocation_pool_start: "{{ item[1]['allocation_pool_start'] | default(omit) }}"
    cidr: "{{ item[1]['cidr'] }}"
    cloud: "{{ item[0]['cloud'] | default(omit) }}"
    dns_nameservers: "{{ item[1]['dns_nameservers'] | default(omit) }}"
    enable_dhcp: "{{ item[1]['enable_dhcp'] | default('yes') }}"
    gateway_ip: "{{ item[1]['gateway_ip'] | default(omit) }}"
    host_routes: "{{ item[1]['host_routes'] | default(omit) }}"
    ip_version: "{{ item[1]['ip_version'] | default('4') }}"
    ipv6_address_mode: "{{ item[1]['ipv6_address_mode'] | default(omit) }}"
    ipv6_ra_mode: "{{ item[1]['ipv6_ra_mode'] | default(omit) }}"
    name: "{{ item[1]['subnet_name'] }}"
    network_name: "{{ item[0]['network_name'] }}"
    no_gateway_ip: "{{ item[1]['no_gateway_ip'] | default('no') }}"
    project: "{{ item[0]['project'] | default(omit) }}"
    state: "{{ item[1]['state'] | default('present') }}"
  with_subelements:
    - "{{ os_networks }}"
    - subnets
  when: os_networks is defined
