- name: 'Create routers and attach networks'
  openstack.cloud.router:
    cloud: "{{ item.cloud | default('') }}"
    state: "{{ item['state'] | default('present') }}"
    name: "{{ item['name'] }}"
    network: "{{ item['network'] | default('public') }}"  # external network
    interfaces: "{{ item['interfaces'] }}"
  with_items: "{{ os_routers }}"
  when: os_routers is defined
